### ISSUE TITLE
Move to springfox organisation

### ISSUE THREAD

**Issue by adrianbk** [springfox/springfox#612]
@dilipkrish putting together some stuff that needs to happen to move and get a release out. We will need to co-ordinate on this as there will be some broad sweeping changes.
 
~~- [ ] Squash all of the commits as part of the 2.0 work to help code review.~~
- [x] New bintray organisation: set up repo, request to host in jcenter, etc..
- [x] Rename all of the source modules to 'springdox' instead of 'mangodocs' 
- [x] Drop the `com.mangofactory` domain from all package names and lets replace with just 'springdox' 
- [x] Create a springdox-swagger-ui module to package a webjar of swagger-ui 2.0
- [x] Get some documentation together on how to use swagger 2.0  (initially something ion the readme)
- [x] Gradle release/publish process needs to be more automated (@adrianbk has some ideas here)

**Comment by dilipkrish** [comment]
Also 
- [ ] Rename the project ```mangodocs``` in github

**Comment by dilipkrish** [comment]
@adrianbk Couple of things about the squashing of the commits, since this is a public branch, lets not push the rewritten history back onto [the refactor branch](https://github.com/springdox/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos). I'd say lets create a very short lived 2.0 candidate branch locally, do all the fix-up, merge to local master and push to origin

Secondly, I was thinking lets use your [petstore service and contract commit](https://github.com/springdox/swagger-springmvc/commit/c31e700620628df45db0a34cdb2f5f3c81705715) as a baseline and squash any commits before that. Mainly cos its useful to see the history of the stuff esply, the contract files, and  changes to the internal models to accommodate 2.0 changes.

**Comment by adrianbk** [comment]
@dilipkrish -  do you mean rename the `swagger-springmvc` repository to `springdox`?

Perhaps we can live without squashing since the branch is gone pubic!

**Comment by dilipkrish** [comment]
:+1: to the repo rename. 

I'd like to squash the initial "thrashing of commits" for sure since it provides very little value. Not really sure what the ideal spot to wind that back to is; your pet store service commit seems like a logical spot.

**Comment by adrianbk** [comment]
@dilipkrish lets decide on a release flow. 
Using this to flesh out how publishing will work.  

## Tasks 
- `release` for releasing real versions to bintray and jcenter
- `snapshot` for releasing snapshots to https://oss.jfrog.org

## :snapshot
Inputs: bintray credentials
Sequence:
- Check that the local git repository is clean
- :clean :check
- Publish snapshot


## :release
Inputs: 
- bintray credentials 
- `release_type` (major,minor, patch)

Sequence:
- Check that the local git repository is clean 
- :clean :check 
- Append 1 to the current version number (version.properties) and save the file 
- perform release to bintray
- create a github release tag
- push git tag and version.properties

The following are some things we may want to bake in to the release flow at a later date
- generating release notes
- publishing documentation
- making sure all issues in the github milestone are closed before releasing
- making sure the same version is not already published (bintray plugin ay be doing this already)
- deploy a sample application

**Comment by dilipkrish** [comment]
@adrianbk :+1: the only thing I'd like to make sure is that the last 2 steps that tag and push, happens at the very last minute when we're absolutely sure the build is golden. It should be very quick but we need to make sure that the push never fails i.e. merge conflicts etc.
